name: npm publication

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository code
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies using package-lock.json
      - run: npm ci

      # Run unit tests
      - run: npm run test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout repository code again for a separate job
      - uses: actions/checkout@v4

      # Setup Node.js and configure npm registry
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Install dependencies again
      - run: npm ci

      # Build a code for browsers
      - run: npm run rollup

      # Publish package to npm registry with authentication token
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
